### ISSUE TITLE
Alternative [Un]Marshal Implementation

### ISSUE THREAD

**Issue by jpillora** [hkwi/gopenflow#1]
Hi Hiroaki, nice work with this project so far. I've written a OF1.3 packer/unpacker in Node and we're slowly moving to Go and I'd like to port something similar to what I have currently to Go.

Please see my question on SO: http://stackoverflow.com/questions/25156204. 

Basically, I'd like a way to provide a struct at build time, then via the `ast` package, meta-program two functions: `Marshal(struct) bytes` and `Unmarshal(bytes) struct`.

So, you have your structs defined in `of_packet_in.go` which defines the `OFP_PACKET_IN` structure, then the proposed program would be run at build time and generate two files: `of_packet_in_[un]marshal.go`, which each implement the respective **methods on the struct**.

This would avoid writing this https://github.com/hkwi/gopenflow/blob/master/ofp4/obj_action.go#L137-L143 style of code for the protocol and also allows fast development of other network protocols, including future versions of openflow.

All protocol parsing strategies would be defined via tags. For example, in my JavaScript example on SO, `length` fields denotes the length for the entire packet. I have others for padding and for lists.

What do you think about this idea?

**Comment by hkwi** [comment]
I switched the implementation to use []byte base type. Another implementation may utilise go generate.

By the way, can I close this ticket?

**Comment by jpillora** [comment]
Closed :) I'm working on a general purpose wire protocol library generator using go generate, will let you know when I get it working
